const pool = require('./index');

const USER_DATA = [
  { name: 'Ellen', role: 'admin' },
  { name: 'Sue', role: 'peasant' },
];

const seedTable = async (tableName, data) => {
  // get a connection from the pool
  let poolClient;
  try {
    poolClient = await pool.connect();
  }
  catch (error) {
    console.log('mysql connection error', error);
    throw error;
  }

  try {
    // await poolClient.query("CREATE DATABASE IF NOT EXISTS " + process.env.PG_DATABASE);
    // await poolClient.query("USE " + process.env.PG_DATABASE);
    await poolClient.query("DROP TABLE IF EXISTS " + tableName);

    let tableCreate = "CREATE TABLE " + tableName + "("
    tableCreate += "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
    tableCreate += ", name VARCHAR(50) NOT NULL";
    tableCreate += ", role VARCHAR(50) NOT NULL";
    tableCreate += ")";

    await poolClient.query(tableCreate);
  }
  catch (error) {
    console.log('create table error', error);
    throw error;
  }

  let insetQuery = "INSERT INTO " + tableName + "(name, role) VALUES($1::text[], $2::text[])";
  let insertValues = [[], []];

  for (let i = 0; i < data.length; i++) {
    const d = data[i];
    insertValues[0].push(d.name);
    insertValues[1].push(d.role);
  }

  let result;
  try {
    result = await poolClient.query(insetQuery, insertValues);
  }
  catch (error) {
    console.log('insert data error', error);
    throw error;
  }
  // Finished with the connection
  poolClient.release();

  // No error, send result
  // callback(false, result);
};

const seed = async (callback) => {
  try {
    await seedTable('users', USER_DATA);
    console.log('User data seeded!');
    callback();
  }
  catch (error) {
    console.log('Problem seeding User data', error);
    callback(true);
  }
};

module.exports = { seed };
